name: Run tests and style checks

on: pull_request

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y python3-setuptools
      - run: pip3 install black>=20.8
      - run: pip3 install pydocstyle flake8
      - run: |
            python3 -m flake8 bempp
            python3 -m flake8 test
        name: Run flake8 checks
      - run: python3 -m pydocstyle bempp/api
        name: Run pydocstyle checks
      - run: | 
            python3 -m black --line-length 88 --check bempp
        name: Run black checks in bempp
      - run: | 
            python3 -m black --line-length 88 --check test
        name: Run black checks on tests
      - run: | 
            python3 -m black --line-length 88 --check .github/scripts
        name: Run black checks on CI scripts

  build-and-test-with-dolfin:
    name: Build Bempp and run tests with DOLFIN
    runs-on: ubuntu-latest
    container: bempp/cl-dev-env-with-dolfin:latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 setup.py install
        name: Install Bempp
      - run: python3 -m pytest -n4 --durations=50 test/unit --has-dolfin 1 --has-dolfinx 0 --has-exafmm 1
        name: Run Bempp unit tests

  build-and-test-with-dolfinx:
    name: Build Bempp and run tests with DOLFINx
    runs-on: ubuntu-latest
    container: bempp/cl-dev-env-with-dolfinx:latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 setup.py install
        name: Install Bempp
      - run: python3 -m pytest -n4 --durations=50 test/unit --has-dolfin 0 --has-dolfinx 1 --has-exafmm 1
        name: Run Bempp unit tests
